Improve code generation of `Ord` and `PartialOrd`
ModProg/derive-where pull request #38
Opened 2022-01-21 13:08 UTC by daxpedda

See code generation tests, should be very self-explanatory.

2022-01-21 13:51 UTC, ModProg requested changes
looks good :+1:

2022-01-21 13:51 UTC, ModProg commented on src/trait_/common_ord.rs
> +					// The last variant is always `Less` then everything.
```suggestion
					// The last variant is always `Greater` then everything.
```

2022-01-21 16:49 UTC, daxpedda commented on src/trait_/common_ord.rs
> +					// The last variant is always `Less` then everything.
Done.

2022-01-22 15:33 UTC, ModProg approved these changes

2022-01-22 20:39 UTC, merged